### ISSUE TITLE
Samples missing

### ISSUE THREAD

**Issue by hanghuiye** [markowetzlab/CINSignatureQuantification#10]
Hello, I've been trying to run quantifyCNSignatures() on our copy number data. I found that when I was using 'drews' as the method, some samples were missing in the SamplexComponent matrix and the final exposures to the 17 CIN signatures. I am curious why, thanks!

**Comment by manivenkatesan** [comment]
I've been having a similar issue. 6 samples of the 501 samples in my analysis dropped out. I suspect it's because some TCGA samples have either none or very few copy number segments after processing with the ASCAT pipeline. I'd recommend you check what's going on with the samples that drop out. I'd be curious what you find.

**Comment by Martingales** [comment]
The missing samples could be due to the hard filter on CNAs that have to be present for samples in order to calculate signature activities properly.

Part of our paper was the task to identify samples with chromosomal instability (CIN). This was not an issue in previous papers (e.g. Macintyre et al., Nat Gen, 2018) as they focussed solely on ovarian cancer. But it was for our project as we had samples from 33 cancer types incl cancer types not known for CIN (e.g. hematologic cancers). In short, we estimated the number of CNAs that had to be present in order to be captured by a previous iteration of the copy number signatures. We found that upwards of 20 CNAs, there is a very high chance that the samples experience CIN and that we can capture it. That is why we filter for samples with less than 20 CNAs where a CNA is defined as a segment unequal to a copy number of 2.
