### ISSUE TITLE
Sex Chromosome Y might not pass the chromosome format check

### ISSUE THREAD

**Issue by zhangyz1997** [markowetzlab/CINSignatureQuantification#15]
Hello~I have encountered an error 
`Error in '$<-.data.frame('*tmp*', "chromosome", value = c(1L, 1L, 1L,`
during quantifyCNSignatures. I have tried figuring out the possible cause of the problem and found the following code in checkChromosomeFormat.R which caused the error, I think.

`chrs <- c(seq.int(1:22),c("X"))`

As I noticed, the code mentioned above might drop chromosome Y and throw out error. The demo dataset does not contain chromosome Y so it works well. Therefore, does it work as intended, or in other words, should I remove the chromosome Y manually to fit the function?

**Comment by Phil9S** [comment]
Hello,

Thank you for reporting this issue. For now if you drop the Y chromosomes in your data prior to quantifying signatures it should work. I will implement a fix and close this issue once available.

**Comment by Phil9S** [comment]
@zhangyz1997 I have implemented a fix in the branch mentioned in this pull request #16. I have checked this fix and it seems to resolve bugs around the presence of the Y chromosome. 

If you could install this branch by running `devtools::install_github("markowetzlab/CINSignatureQuantification", build_vignettes = TRUE,ref="checkChromosomeFormat-bug")` and let me know if it resolves the bug, that would be very helpful, otherwise I will merge the pull request and presume it has fixed the issue.

**Comment by zhangyz1997** [comment]
> @zhangyz1997 I have implemented a fix in the branch mentioned in this pull request #16. I have checked this fix and it seems to resolve bugs around the presence of the Y chromosome.
> 
> If you could install this branch by running `devtools::install_github("markowetzlab/CINSignatureQuantification", build_vignettes = TRUE,ref="checkChromosomeFormat-bug")` and let me know if it resolves the bug, that would be very helpful, otherwise I will merge the pull request and presume it has fixed the issue.

It just works as expected. Thanks for you and your team's great work!
